### ISSUE TITLE
Mislalignment

### ISSUE THREAD

**Issue by Otter999** [stackTom/Ortho4XP_FSX_P3D#21]
Jersey misalignment (ZL16)
N49* 12.51'
W2* 11.26'

Corsica misalignment (ZL15)
N42* 2.33'
E9* 24.40'

![Corsia_ZL15_misalignment](https://user-images.githubusercontent.com/82292754/114305054-c0027f00-9ad6-11eb-91fc-3f3a05f88504.png)
![Corsica_zl15_misalignment](https://user-images.githubusercontent.com/82292754/114305059-c3960600-9ad6-11eb-8836-8e7fce43315b.png)
![Jersey16,misalignment](https://user-images.githubusercontent.com/82292754/114305062-c7c22380-9ad6-11eb-8cf7-aa3de276e5f6.png)

**Comment by stackTom** [comment]
Closing, since Ortho4FS9 has been abandoned in favor of FSEarthTiles.
