### ISSUE TITLE
Seasons

### ISSUE THREAD

**Issue by Otter999** [stackTom/Ortho4XP_FSX_P3D#22]
Although seasons are set to false in the cfg file, Ortho4FS9 creates bmp files for seasons.
5 seasons HW, W, S, F, Ss and Lm... dunno what that is. Is this the night texture?

**Comment by Otter999** [comment]
On all zoom levels.

**Comment by stackTom** [comment]
Even if seasons are false, I still build all the seasons because otherwise, an empty tile will show in place of the tile if the sim is in a season that it didn't have built for it. This is different than FSX where I can specify all the months for which to show a texture in the inf file. So in FSX, I just set non-built season months to display with the summer texture. I can't do this in FS9. In FS9, I have to build all the seasons which are set to False and build them to use the Summer texture.

**Comment by Otter999** [comment]
So, if I set time/season always just to summer in the sim, do I still need all these other textures? In other words, I will only fly in summer. In this case could I delete Winter, High Winter, Spring and Fall and just keep Summer and Night? It would reduce the amount of memory size significantly.

**Comment by stackTom** [comment]
I never thought of this. Can you delete all non summer seasons and see what happens?

Also, I didn't consider some people only want to fly in a certain season. Right now, what I do is, I only create different texture photos for the seasons which are set to True. But for seasons which are set to false, I still tell resample to create the season but these seasons use one of the other already created textures. If all textures are set to false, I just create a summer texture and tell resample to create all seasons with this Summer texture.

Do you think I should tell resample to only create seasons specified in the cfg? Even if it means an empty gray square if you select those seasons you haven't created? I thought my solution was better, as I personally like the fsx behavior of at least 1 season for all months so something always displays.

**Comment by Otter999** [comment]
I don't know if I follow. The sat images are usually just summer as far as I know. So, you always set summer time in the sim. That's what I do, also to have better color match with tree colors etc. So, if there are no seasonal photos, why bother with it. Would FS9 just display a grey area if you pick winter for example? In that case, it might be better to have all seasonal textures and everyone can decide what he wants to delete. I will try by deleting the others and see what happens. There are also Ln textures. These are night textures? I would leave those.

**Comment by stackTom** [comment]
Ln is night.

And yes, if you only tell resample to build summer for example, choosing any other season will result in a big gray square where the tile should be. It doesn't even show the default scenery.

If I remember correctly, in fsx/p3d, if you only create one season but don't specify all the months, then it shows the default scenery in that month. For example, say I didn't assign the month of January to a season. Flying in January will show the default scenery (if I remember correctly).

Fs9 just shows a gray square... this is why I tell resample to create all seasons. Even if you put all of them to false. However, I only make different color textures for the seasons set to True. The ones set to False just use the summer texture.

How does FSET do it? Maybe we can do what they do.

**Comment by Otter999** [comment]
In FSET you can choose and it won't create all those files.

**Comment by Otter999** [comment]
Yes, the bmp files made with Ortho only show in its season. Otherwise gray.
The bmp files made with FSET (even though choosing no sesason or just summer) show in all seasons in the sim. So there is a difference somewhere. Inf  file?

**Comment by stackTom** [comment]
Closing, since Ortho4FS9 has been abandoned in favor of FSEarthTiles.
