### ISSUE TITLE
Rebuild of Ortho4XP.cfg

### ISSUE THREAD

**Issue by Otter999** [stackTom/Ortho4XP_FSX_P3D#24]
When editing config menu and applying it to the cfg file, the newly generated cfg file is missing these lines:

#FSX_P3D_resample_loc=F:\\ortho4xpvm\\resample.exe
FS9_resample_loc=C:\\ResampleFS9\\resampleFS2004.exe
FS9_imagetool_loc=C:\\ResampleFS9\\imagetool.exe
#ESP_scenproc_loc=C:\\Userddds\\fery2\\Desktop\\scenproc_latest_development_release_x64\\scenProc.exe
#ESP_scenproc_script=default.spc
max_resample_processes=8
create_ESP_night=True
create_ESP_summer=True
create_ESP_spring=False
create_ESP_fall=False
create_ESP_winter=False
create_ESP_hard_winter=False

**Comment by stackTom** [comment]
Fixed
