### ISSUE TITLE
Memory size

### ISSUE THREAD

**Issue by Otter999** [stackTom/Ortho4XP_FSX_P3D#25]
Higher zoom levels  create less files in the texture folder and therefore less mb. The only thing that increases with higher zoom levels is the amount of bgl files in the scenery folder. But those are just 2kb each. Here the number for +49-003 (Jersey):

BL14 **689mb**  texture folder files 16.530 **(which is way too much for a tiny island like Jersey)**
BL15 371mb  texture folder files  8.904  **(which is still way too much for a tiny island like Jersey)**
BL16 212mb  texture folder files  5.100
BL17 126mb  texture folder files  3.036

Only using very high zoom levels creates a reasonable memory. If I am going to do just teh South of England, it would be a huge amount of GB at a low zoom level of just 14.

**Comment by stackTom** [comment]
Resample for fs2004 is strange... I am not sure why this is happening, but if the tile displays properly in the sim, that is what matters.
