### ISSUE TITLE
Zoom Level 18

### ISSUE THREAD

**Issue by Otter999** [stackTom/Ortho4XP_FSX_P3D#28]
Not working it seems: 
![Microsoft Flight Simulator 2004 - A Century of Flight 4_13_2021 6_33_26 PM](https://user-images.githubusercontent.com/82292754/114589857-5fb33f00-9c88-11eb-8350-78f8fc22a6df.png)

**Comment by stackTom** [comment]
Closing, since Ortho4FS9 has been abandoned in favor of FSEarthTiles.
