### ISSUE TITLE
Airports and misalignment

### ISSUE THREAD

**Issue by Otter999** [stackTom/Ortho4XP_FSX_P3D#29]
+51-002 at ZL 16, Bing

It's a common problem that airports are not correctly positioned in FS9 or FSX and therefore photoreal scenery and generic airport don't match. However, with Ortho4FS9 the issue is worse than with FSET. Here at EGVN:

FSET:
![Microsoft Flight Simulator 2004 - A Century of Flight 4_13_2021 8_45_26 PM](https://user-images.githubusercontent.com/82292754/114604771-9cd3fd00-9c99-11eb-9521-93ac49dc0e89.png)

And here with Ortho (sorry not the same angle):
![Microsoft Flight Simulator 2004 - A Century of Flight 4_13_2021 8_23_25 PM](https://user-images.githubusercontent.com/82292754/114604819-ad847300-9c99-11eb-8faf-396b1ba87585.png)

As you can see above the misalignment in the Ortho scenery is really bad and then we have a terrain mismatch on top of it cutting through the scenery (at the right).

Just flying for 10 minutes I get 3+ mismatches. ALL airports are very dislocated in the Ortho scenery. So, honestly, sorry to say that, it's no fun. I might do some testing more to see where Ortho4FS9 can be useful, but I can't picture this right now. It's just too bad for my taste.
![Microsoft Flight Simulator 2004 - A Century of Flight 4_13_2021 8_29_39 PM](https://user-images.githubusercontent.com/82292754/114605305-3dc2b800-9c9a-11eb-924d-213ced5606a3.png)
![Microsoft Flight Simulator 2004 - A Century of Flight 4_13_2021 8_25_08 PM](https://user-images.githubusercontent.com/82292754/114605322-42876c00-9c9a-11eb-8bda-76f3919f07ed.png)
Same here above: airport totally off and a whole line cutting through the scenery (at the right)

![Microsoft Flight Simulator 2004 - A Century of Flight 4_13_2021 8_20_27 PM](https://user-images.githubusercontent.com/82292754/114605336-461af300-9c9a-11eb-8839-19324ad390b9.png)
![Microsoft Flight Simulator 2004 - A Century of Flight 4_13_2021 8_17_43 PM](https://user-images.githubusercontent.com/82292754/114605350-4a471080-9c9a-11eb-93d2-adc1def929b6.png)
![Microsoft Flight Simulator 2004 - A Century of Flight 4_13_2021 8_11_07 PM](https://user-images.githubusercontent.com/82292754/114605370-4e732e00-9c9a-11eb-9ac4-a033e52d384e.png)

I stopped the testing after 10 minutes. So, I didn't fly the whole test area. I am not sure if you should release Ortho4FS9 as it is right now. I probably won't use it. Sorry, mate.

**Comment by stackTom** [comment]
Closing, since Ortho4FS9 has been abandoned in favor of FSEarthTiles.
