### ISSUE TITLE
[Feature suggestion]Add a feature to try the download if the image contains white squares

### ISSUE THREAD

**Issue by Sgambe33** [stackTom/Ortho4XP_FSX_P3D#32]
Recently I noticed that once I download a tile, a few images appear with white squares inside them because, as the log says, it wasn't possible to obtain part of the image. If I delete these images and start the download again, the script will download the missing images correcly. So I was wondering if it's possible to implement a feature that automatically checks wether or not the image contains the white square and if so, download the image again.

**Comment by stackTom** [comment]
Will have to investigate. I didn't modify this part of the code, so that's an inherent issue in Ortho4XP.

My development is primarily focused on FSEarthTiles lately though: https://github.com/stackTom/FSEarthTiles. I recommend it over ortho4xp_fsx_p3d for making ortho for fs9, fsx, p3d, and msfs. It has algorithms to improve image quality (by reducing distortion) for the fs9, fsx, p3d resample process.

**Comment by Sgambe33** [comment]
> Will have to investigate. I didn't modify this part of the code, so that's an inherent issue in Ortho4XP.
> 
> My development is primarily focused on FSEarthTiles lately though: https://github.com/stackTom/FSEarthTiles. I recommend it over ortho4xp_fsx_p3d for making ortho for fs9, fsx, p3d, and msfs. It has algorithms to improve image quality (by reducing distortion) for the fs9, fsx, p3d resample process.

Great work there too but I feel like FSET creates to many images on my HDD: last time I used it for a tile it created more than 50k images at zoom 2. On Ortho4Fsx with zoom level at 16 it generated only 500 images. Anyway, it's not an important feature the one I mentioned so there's no rush.

**Comment by stackTom** [comment]
Both programs split images differently. But at the end of the day, both download only the amount of tiles required to create the requested imagery. Ortho4xp tends to create bigger images. Fset smaller images but more of them.

**Comment by stackTom** [comment]
Also, 50k sounds excessive. That might be the images in the cache (I can assure you ortho4xp downloads the same amount of images, it just never saves them to disk until it combines them into a larger image). You can always disable the cache in FSET if you wish 👍.
