### ISSUE TITLE
Problem using zoom level

### ISSUE THREAD

**Issue by Pgz15** [stackTom/Ortho4XP_FSX_P3D#36]
When I try to use the zoom level, it creates several folders (Example: BL16, BL17, BL18 and BL19) and thus generates the "ADDON SCENERY" folder only in the "BL16" folder and does not convert the other files that are in the other folders to .bgl and when I activate "ADDON SCENERY" in the simulator it only recognizes the part where I placed the
zoom 16, What could be done in this case?

**Comment by stackTom** [comment]
I never added the multi zoom level function unfortunately. That only works for the xplane mode.

**Comment by Pgz15** [comment]
Wouldn't it be possible to put it on? It greatly improves the ortho quality and also reduces the file size, if possible include

**Comment by Pgz15** [comment]
Wouldn't it be possible to put it on? It greatly improves the ortho quality and also reduces the file size, if possible include
